name: Bot script
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt update && sudo apt install python3 python3-pip -y
          pip install python-telegram-bot requests

      - name: Run bot script
        run: |
           python3 m23bot.py
