name: Check firmware update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
  push:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Brazil
          - model: "SM-M236B"
            region: "ZTO"
          # India
          - model: "SM-E236B"
            region: "INS"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Compare latest version with current version
        run: |
          need_update=0
          latest=`curl --retry 5 --retry-delay 5 http://fota-cloud-dn.ospserver.net/firmware/${{ matrix.region }}/${{ matrix.model }}/version.xml | grep latest | sed 's/^[^>]*>//' | sed 's/<.*//'`
          latest_short=`echo $latest | cut -d'/' -f1`
          current=`cat current.${{ matrix.model }}_${{ matrix.region }}` || need_update=1
          [[ $latest != $current ]] && need_update=1
          echo "latest_version=$latest" >> $GITHUB_ENV
          echo "latest_shortversion=$latest_short" >> $GITHUB_ENV
          echo "need_update=$need_update" >> $GITHUB_ENV

      - name: Cleanup space
        if: env.need_update == 1
        run: |
          sudo apt-get remove --purge -y "php*" "dotnet*" "mysql*" "nodejs*" "clang*" "google*"
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/local

      - name: Update current version
        if: env.need_update == 1
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin ${{github.ref}} --ff-only
          echo ${{ env.latest_version }} > current.${{ matrix.model }}_${{ matrix.region }}
          git add current.${{ matrix.model }}_${{ matrix.region }}
          if [[ "${{ matrix.model }}" == "SM-M236B" ]]; then
              git commit -m "Nova Atualização para o Samsung Galaxy M23! ${{ env.latest_version }}"
          else
              git commit -m "New Update for Samsung Galaxy F23! ${{ env.latest_version }}"
          fi
          git tag "${{ env.latest_shortversion }}_${{ matrix.region }}"

      - name: Push changes to repo
        if: env.need_update == 1
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.TOKEN }}

      - name: Start NotifierBot M23
        if: env.need_update == 1
        env:
          CHAT_ID: ${{ secrets.CHAT_ID_M23 }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Start NotifierBot F23
        if: env.need_update == 1
        env:
          CHAT_ID: ${{ secrets.CHAT_ID_F23 }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
